name: recharge_max
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.6.0
  intl: ^0.17.0
  flutter_svg: ^2.0.9
  file_picker:
  lottie: ^3.0.0
#  firebase_messaging: ^14.9.2
#  firebase_core: ^2.27.0
#  firebase_analytics: ^10.10.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  share: ^2.0.4
  dropdown_search: ^5.0.6


  confetti: ^0.7.0
  audioplayers: ^6.0.0


  flutter_bloc: ^8.1.2
  flutter_phoenix: ^1.1.1
  flutter_screenutil: ^5.7.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^7.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.0
  path_provider: ^2.0.14
  dartz: ^0.10.1
  equatable: ^2.0.5
  rxdart: ^0.27.7

  shimmer: ^3.0.0

  calendar_date_picker2: 1.0.6
  motion_toast: ^2.11.0
  image_picker: ^0.8.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  jwt_decoder: ^2.0.1
  webview_flutter: ^4.1.0

  date_format:
  multi_dropdown:
  auto_size_text:
  dotted_border: ^2.1.0
  pdf: ^3.10.8
  share_plus: ^9.0.0
  printing: ^5.11.1
  floating_draggable_widget: ^2.3.0
  pin_code_fields: ^8.0.1
  pdfx: ^2.6.0
  smooth_page_indicator: ^1.2.1
  internet_file: ^1.2.0
  uuid:

  flutter_typeahead:
  dotted_line: ^3.2.3
  timeline_tile: ^2.0.0
  flutter_local_notifications:

  flutter_fortune_wheel: ^1.3.1

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/start_spin.wav
    - assets/sounds/win.wav
    - assets/images/
    - assets/newSvg/
    - assets/fonts/geist/
    - .env.dev
    - .env.prod

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/geist/Geist-Black.ttf
          weight: 900
        - asset: assets/fonts/geist/Geist-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/geist/Geist-Bold.ttf
          weight: 600
        - asset: assets/fonts/geist/Geist-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/geist/Geist-Medium.ttf
          weight: 400
        - asset: assets/fonts/geist/Geist-Regular.ttf
          weight: 300
        - asset: assets/fonts/geist/Geist-Light.ttf
          weight: 200
        - asset: assets/fonts/geist/Geist-ExtraLight.ttf
          weight: 100

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf

